### ISSUE TITLE
Implement `depends_on` key

### ISSUE THREAD

**Issue by vpetersson** [sbomify/github-action#25]
As we're bringing in more community SBOMs, it would be great to be able to leverage these SBOMs as part of a bigger picture. 

The way i anticipate this to work would be something like this. Imagine you're using `cgr.dev/chainguard/python` as the runtime image for your Python based application. During the build time, you would then capture the SHA of the image (`docker inspect "cgr.dev/chainguard/${{ python:latest" | jq -r '.[].Id' | cut -d -f2'`). 

When you then build your SBOM from say the `poetry.lock` file, you'd include this under `DEPENDS_ON` like this:

```yaml       
- name: Upload SBOM to sbomify
   uses: sbomify/github-action@master
   env:
     TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
      COMPONENT_ID: ${{ matrix.image.component_id }}
      LOCK_FILE: 'poetry.lock'
      DEPENDS_ON: cgr.dev/chainguard/python:IMAGE_SHA
     [...]
```

Behind the scenes, the GitHub Action module will make an API call and look up this and link it to the corresponding SBOM. While this should work both for SPDX and CycloneDX, in the case of CycloneDX, the part we would inject into the SBOM would look something like this:

```json
  "dependencies": [
    {
      "ref": "[top level reference]",
      "dependsOn": [
        "[...]"
      ],
      "bomLinks": [
        {
          "url": "https://app.sbomify.com/[....]",
          "hashes": [
            {
              "alg": "SHA-256",
              "content": "[redacted]"
            }
          ]
        }
      ]
    }
  ]
```
